<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>13</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ModEntry>Scripts/Entry.cs</ModEntry>
    <ModId>RimuruTempest</ModId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Alchyr.Sts2.BaseLib" Version="3.4.0" />
    <PackageReference Include="STS2.RitsuLib.Compat.0.107.1" Version="0.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>D:\SteamFolder\steamapps\common\Slay the Spire 2\data_sts2_windows_x86_64\sts2.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
